---
title: "R Notebook"
output: html_notebook
---


```{r}
library(exploratory)

# Steps to produce the output
exploratory::read_delim_file("https://www.quandl.com/api/v3/datasets/NVCA/VENTURE_3_10B.csv?api_key=8DCDi39Y9uYHU9jsKxry&end_date=2016-12-31" , ",", quote = "\"", skip = 0 , col_names = TRUE , na = c("","NA") , locale=locale(encoding = "UTF-8", decimal_mark = "."), trim_ws = FALSE , progress = FALSE) %>% exploratory::clean_data_frame() %>%
  gather(industry, deals, -Date, -Total, na.rm = TRUE)
```


```{r}
# Load required packages.
library(janitor)
library(lubridate)
library(hms)
library(tidyr)
library(stringr)
library(readr)
library(forcats)
library(RcppRoll)
library(dplyr)
library(exploratory)

# Steps to produce the output
exploratory::read_delim_file("VentureCapitalInvestmentsbyIndustry.csv" , ",", 
                             quote = "\"", skip = 0 , col_names = TRUE , 
                             na = c("","NA") , 
                             locale=locale(encoding = "UTF-8", decimal_mark = "."), 
                             trim_ws = FALSE , progress = FALSE) %>% 
    exploratory::clean_data_frame() %>%
    # select(-Total) #%>%
    gather(industry, amounts, -Date) %>%
      filter(industry != "Other") %>%
      mutate(industry = str_replace(industry, "and", "&")) %>%
      group_by(industry) %>%
      do_prophet(Date, amounts, 10, time_unit = "year", fun.aggregate = sum)
```

